var ams = require('ams')
, path = require('path')
, mongoose = require('mongoose')
, models = require('./models')
, publicDir = __dirname + '/public'
, fontsDir = publicDir + '/fonts'
, prod = process.env.NODE_ENV === 'production';

module.exports = function() {
    configureFiles();
    initializeDefaultCardsDb();
};

function configureFiles() {
    var options = {
	uglifyjs: prod,
	jstransport: false,
	cssabspath: false,
	cssdataimg: false,
	texttransport: false
    };
    ams.build
	.create(publicDir)
	.add(path.resolve(path.join(__dirname, 'client'), './client.js'))
	.add(path.resolve(path.join(__dirname, 'dependencies', 'headjs/src'), './load.js'))
	.process(options)
	.write(publicDir)
	.end();
};

function initializeDefaultCardsDb() {
    var WhiteDeck = models.WhiteDeck;
    WhiteDeck.find({ name : /default/i }, function (err, deck) {
	if (0 >= deck.length) {
	    var basewhite = new WhiteDeck({
		name : 'default',
		cards : getDefaultWhiteDeck()
	    });
	    basewhite.save(function (err, deck) {
		if (err) {
		    console.log("ERROR DEF WHITE DECK: " + err.toString());
		}
	    });
	}
    });
    var BlackDeck = models.BlackDeck;
    BlackDeck.find({ name : /default/i }, function (err, deck) {
	if (0 >= deck.length) {
	    var baseblack = new BlackDeck({
		name : 'default',
		cards : getDefaultBlackDeck()
	    });
	    baseblack.save(function (err, deck) {
		if (err) {
		    console.log("ERROR DEF BLACK DECK: " + err.toString());
		}
	    });
	}
    });
}

function getDefaultBlackDeck() {
    var BlackCard = models.BlackCard;
    return [new BlackCard({ desc : "How did I lose my virginity?", type : 1 }),
	    new BlackCard({ desc : "Why can't I sleep at night?", type : 1 }),
	    new BlackCard({ desc : "What's that smell?", type : 1 }),
	    new BlackCard({ desc : "I got 99 problems but _____ ain't one.", type : 1 }),
	    new BlackCard({ desc : "Maybe she's born with it. Maybe it's _____.", type : 1 }),
	    new BlackCard({ desc : "What's the next Happy Meal toy?", type : 1 }),
	    new BlackCard({ desc : "Here is the church. Here is the steeple. Open the doors and there is _____.", type : 1 }),
	    new BlackCard({ desc : "It's a pity that kids these days are all getting involved with _____.", type : 1 }),
	    new BlackCard({ desc : "During his childhood, Salvador Dali produced hundreds of paintings of _____.", type : 1 }),
	    new BlackCard({ desc : "Alternative medicine is now embracing the curative powers of _____.", type : 1 }),
	    new BlackCard({ desc : "What's that sound?", type : 1 }),
	    new BlackCard({ desc : "What ended my last relationship?", type : 1 }),
	    new BlackCard({ desc : "MTV's new reality show features eight washed-up celebrities living with _____.", type : 1 }),
	    new BlackCard({ desc : "I drink to forget _____.", type : 1 }),
	    new BlackCard({ desc : "I'm sorry, Professor, but I couldn't complete my homework because of _____.", type : 1 }),
	    new BlackCard({ desc : "What is Batman's guilty pleasure?", type : 1 }),
	    new BlackCard({ desc : "This is the way the world ends\ This is the way the world ends\ Not with a bang but with _____.", type : 1 }),
	    new BlackCard({ desc : "What's a girl's best friend?", type : 1 }),
	    new BlackCard({ desc : "TSA guidelines now prohibit _____ on airplanes.", type : 1 }),
	    new BlackCard({ desc : "_____. That's how I want to die.", type : 1 }),
	    new BlackCard({ desc : "In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time.", type : 1 }),
	    new BlackCard({ desc : "What does Dick Cheney prefer?", type : 1 }),
	    new BlackCard({ desc : "Dear Abby, I'm having some trouble with _____ and would like your advice.", type : 1 }),
	    new BlackCard({ desc : "Instead of coals, Santa now gives the bad children _____.", type : 1 }),
	    new BlackCard({ desc : "What's the most emo?", type : 1 }),
	    new BlackCard({ desc : "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?", type : 1 }),
	    new BlackCard({ desc : "A romantic candlelit dinner would be incomplete without _____.", type : 1 }),
	    new BlackCard({ desc : "_____. Betcha can't have just one!", type : 1 }),
	    new BlackCard({ desc : "White people like _____.", type : 1 }),
	    new BlackCard({ desc : "_____. High five, bro.", type : 1 }),
	    new BlackCard({ desc : "Next from J.K. Rowling: Harry Potter and the Chamber of _____.", type : 1 }),
	    new BlackCard({ desc : "BILLY MAYS HERE FOR _____.", type : 1 }),
	    new BlackCard({ desc : "War! What is it good for?", type : 1 }),
	    new BlackCard({ desc : "During sex, I like to think about _____.", type : 1 }),
	    new BlackCard({ desc : "What are my parents hiding from me?", type : 1 }),
	    new BlackCard({ desc : "What will always get you laid?", type : 1 }),
	    new BlackCard({ desc : "In L.A. County Jail, word is you can trade 200 cigarettes for _____.", type : 1 }),
	    new BlackCard({ desc : "What did I bring back from Mexico?", type : 1 }),
	    new BlackCard({ desc : "What don't you want to find in your Chinese food?", type : 1 }),
	    new BlackCard({ desc : "What will I bring back in time to convince people that I am a powerful wizard?", type : 1 }),
	    new BlackCard({ desc : "How am I maintaining my relationship status?", type : 1 }),
	    new BlackCard({ desc : "_____. It's a trap!", type : 1 }),
	    new BlackCard({ desc : "Coming to Broadway this season, _____: The Musical.", type : 1 }),
	    new BlackCard({ desc : "When the U.S. raced the Soviets to the moon, the Mexican government funneled millions of pesos into research on _____.", type : 1 }),
	    new BlackCard({ desc : "After the earthquake, Sean Penn brought _____ to the people of Haiti.", type : 1 }),
	    new BlackCard({ desc : "Next on ESPN2, the World Series of _____.", type : 1 }),
	    new BlackCard({ desc : "But before I kill you, Mr. Bond, I must show you _____.", type : 1 }),
	    new BlackCard({ desc : "What gives me uncontrollable gas?", type : 1 }),
	    new BlackCard({ desc : "What do old people smell like?", type : 1 }),
	    new BlackCard({ desc : "The class field trip was completely ruined by _____.", type : 1 }),
	    new BlackCard({ desc : "When Pharaoh remained unmoved, Moses called down a Plague of _____.", type : 1 }),
	    new BlackCard({ desc : "What's my secret power?", type : 1 }),
	    new BlackCard({ desc : "What's there a ton of in heaven?", type : 1 }),
	    new BlackCard({ desc : "What would grandma find disturbing, yet oddly charming?", type : 1 }),
	    new BlackCard({ desc : "What did the U.S. airdrop to the children of Afghanistan?", type : 1 }),
	    new BlackCard({ desc : "What helps Obama unwind?", type : 1 }),
	    new BlackCard({ desc : "What did Vin Diesel eat for dinner?", type : 1 }),
	    new BlackCard({ desc : "_____: good to the last drop.", type : 1 }),
	    new BlackCard({ desc : "Why am I sticky?", type : 1 }),
	    new BlackCard({ desc : "What gets better with age?", type : 1 }),
	    new BlackCard({ desc : "_____: kid-tested, mother-approved.", type : 1 }),
	    new BlackCard({ desc : "Daddy, why is mommy crying?", type : 1 }),
	    new BlackCard({ desc : "What's Teach for America using to inspire inner city students to succeed?", type : 1 }),
	    new BlackCard({ desc : "Studies show that lab rats navigate mazes 50% faster after being exposed to _____.", type : 1 }),
	    new BlackCard({ desc : "Life for American Indians was forever changed when the White man introduced them to _____.", type : 1 }),
	    new BlackCard({ desc : "I don't know what weapons World War III will be fought, but World War IV will be fought with _____.", type : 1 }),
	    new BlackCard({ desc : "Why do I hurt all over?", type : 1 }),
	    new BlackCard({ desc : "What am I giving up for Lent?", type : 1 }),
	    new BlackCard({ desc : "In Michael Jackson's final moments, he thought about _____.", type : 1 }),
	    new BlackCard({ desc : "The Smithsonian Museum of Natural History has just opened an interactive exhibit on _____.", type : 1 }),
	    new BlackCard({ desc : "When I am President of the United States, I will create the Department of _____.", type : 1 }),
	    new BlackCard({ desc : "When I am a billionaire, I shall erect a 50-foot statue to commemorate _____.", type : 1 }),
	    new BlackCard({ desc : "What's my anti-drug?", type : 1 }),
	    new BlackCard({ desc : "What never fails to liven up the party?", type : 1 }),
	    new BlackCard({ desc : "What's the new fad diet?", type : 1 }),
	    new BlackCard({ desc : "Major League Baseball has banned _____ for giving players an unfair advantage.", type : 1 }),
	    new BlackCard({ desc : "On the eight day, God created _____ and said it was good.", type : 1 })];
}

function getDefaultWhiteDeck() {
    var WhiteCard = models.WhiteCard;
    return [new WhiteCard({ desc : "Being on fire." }),
	    new WhiteCard({ desc : "Racism." }),
	    new WhiteCard({ desc : "Old-people smell." }),
	    new WhiteCard({ desc : "A micropenis." }),
	    new WhiteCard({ desc : "Women in yogurt commercials." }),
	    new WhiteCard({ desc : "Classist undertones." }),
	    new WhiteCard({ desc : "Not giving a shit about the Third World." }),
	    new WhiteCard({ desc : "Sexting." }),
	    new WhiteCard({ desc : "Roofies." }),
	    new WhiteCard({ desc : "A windmill full of corpses." }),
	    new WhiteCard({ desc : "The gays." }),
	    new WhiteCard({ desc : "Oversized lollipops." }),
	    new WhiteCard({ desc : "African children." }),
	    new WhiteCard({ desc : "An asymmetric boob job." }),
	    new WhiteCard({ desc : "Bingeing and purging." }),
	    new WhiteCard({ desc : "The hardworking Mexican." }),
	    new WhiteCard({ desc : "An Oedipus complex." }),
	    new WhiteCard({ desc : "A tiny horse." }),
	    new WhiteCard({ desc : "Boogers." }),
	    new WhiteCard({ desc : "Penis envy." }),
	    new WhiteCard({ desc : "Barack Obama." }),
	    new WhiteCard({ desc : "My humps." }),
	    new WhiteCard({ desc : "The Tempur-pedic Swedish Sleep System." }),
	    new WhiteCard({ desc : "Scientology." }),
	    new WhiteCard({ desc : "Dry heaving." }),
	    new WhiteCard({ desc : "Skeletor." }),
	    new WhiteCard({ desc : "Darth Vader." }),
	    new WhiteCard({ desc : "Figgy pudding." }),
	    new WhiteCard({ desc : "Chutzpah." }),
	    new WhiteCard({ desc : "Five-Dollar Footlongs." }),
	    new WhiteCard({ desc : "Elderly Japanese Men." }),
	    new WhiteCard({ desc : "Free Samples." }),
	    new WhiteCard({ desc : "Estrogen." }),
	    new WhiteCard({ desc : "Sexual tension." }),
	    new WhiteCard({ desc : "Famine." }),
	    new WhiteCard({ desc : "A stray pube." }),
	    new WhiteCard({ desc : "Men." }),
	    new WhiteCard({ desc : "Heartwarming orphans." }),
	    new WhiteCard({ desc : "Genital piercings." }),
	    new WhiteCard({ desc : "A bag of magic beans." }),
	    new WhiteCard({ desc : "Repression." }),
	    new WhiteCard({ desc : "Prancing." }),
	    new WhiteCard({ desc : "My relationship status." }),
	    new WhiteCard({ desc : "Overcompensation." }),
	    new WhiteCard({ desc : "Peeing a little bit." }),
	    new WhiteCard({ desc : "Pooping back and forth. Forever." }),
	    new WhiteCard({ desc : "Eating all of the cookies before the AIDS bake sale." }),
	    new WhiteCard({ desc : "Testicular torsion." }),
	    new WhiteCard({ desc : "The Devil himself." }),
	    new WhiteCard({ desc : "The World of Warcraft." }),
	    new WhiteCard({ desc : "Dick Cheney." }),
	    new WhiteCard({ desc : "MechaHitler." }),
	    new WhiteCard({ desc : "Being fabulous." }),
	    new WhiteCard({ desc : "Pictures of boobs." }),
	    new WhiteCard({ desc : "A caress of the inner thigh." }),
	    new WhiteCard({ desc : "The Amish." }),
	    new WhiteCard({ desc : "Pabst Blue Ribbon." }),
	    new WhiteCard({ desc : "Lance Armstrong's missing testicle." }),
	    new WhiteCard({ desc : "Pedophiles." }),
	    new WhiteCard({ desc : "The Pope." }),
	    new WhiteCard({ desc : "Flying sex snakes." }),
	    new WhiteCard({ desc : "Sarah Palin." }),
	    new WhiteCard({ desc : "Feeding Rosie O'Donnell." }),
	    new WhiteCard({ desc : "Sexy pillow fights." }),
	    new WhiteCard({ desc : "Another goddamn vampire movie." }),
	    new WhiteCard({ desc : "Cybernetic enhancements." }),
	    new WhiteCard({ desc : "Civilian casualities." }),
	    new WhiteCard({ desc : "Scrubbing under the folds." }),
	    new WhiteCard({ desc : "The female orgasm." }),
	    new WhiteCard({ desc : "Bitches." }),
	    new WhiteCard({ desc : "The Boy Scouts of America." }),
	    new WhiteCard({ desc : "Auschwitz." }),
	    new WhiteCard({ desc : "Finger painting." }),
	    new WhiteCard({ desc : "The Care Bear Stare." }),
	    new WhiteCard({ desc : "The Jews." }),
	    new WhiteCard({ desc : "Being marginialized." }),
	    new WhiteCard({ desc : "The Blood of Christ." }),
	    new WhiteCard({ desc : "Dead parents." }),
	    new WhiteCard({ desc : "Seduction." }),
	    new WhiteCard({ desc : "Dying of dysentery." }),
	    new WhiteCard({ desc : "Mr Clean, right behind you." }),
	    new WhiteCard({ desc : "The Virginia Tech Massacre." }),
	    new WhiteCard({ desc : "Jewish fraternities." }),
	    new WhiteCard({ desc : "Hot Pockets." }),
	    new WhiteCard({ desc : "Natalie Portman." }),
	    new WhiteCard({ desc : "Agriculture." }),
	    new WhiteCard({ desc : "Judge Judy." }),
	    new WhiteCard({ desc : "Surprised sex!" }),
	    new WhiteCard({ desc : "The homosexual lifestyle." }),
	    new WhiteCard({ desc : "Robert Downey, Jr." }),
	    new WhiteCard({ desc : "The Trail of Tears." }),
	    new WhiteCard({ desc : "An M. Night Shyamalan plot twist." }),
	    new WhiteCard({ desc : "A big hoopla about nothing." }),
	    new WhiteCard({ desc : "Electricity." }),
	    new WhiteCard({ desc : "Amputees." }),
	    new WhiteCard({ desc : "Throwing a virgin into a volcano." }),
	    new WhiteCard({ desc : "Italians." }),
	    new WhiteCard({ desc : "Explosions." }),
	    new WhiteCard({ desc : "A good sniff." }),
	    new WhiteCard({ desc : "Destroying the evidence." }),
	    new WhiteCard({ desc : "Children on leashes." }),
	    new WhiteCard({ desc : "Catapults." }),
	    new WhiteCard({ desc : "One trillion dollars." }),
	    new WhiteCard({ desc : "Friends with benefits." }),
	    new WhiteCard({ desc : "Dying." }),
	    new WhiteCard({ desc : "Silence." }),
	    new WhiteCard({ desc : "An honest cop with nothing left to lose." }),
	    new WhiteCard({ desc : "YOU MUST CONSTRUCT ADDITIONAL PYLONS." }),
	    new WhiteCard({ desc : "Justin Bieber." }),
	    new WhiteCard({ desc : "The Holy Bible." }),
	    new WhiteCard({ desc : "Balls." }),
	    new WhiteCard({ desc : "Praying the gay away." }),
	    new WhiteCard({ desc : "Teenage pregnancy." }),
	    new WhiteCard({ desc : "German dungeon porn." }),
	    new WhiteCard({ desc : "The invisible hand." }),
	    new WhiteCard({ desc : "My inner demons." }),
	    new WhiteCard({ desc : "Powerful thighs." }),
	    new WhiteCard({ desc : "Getting naked and watching Nickelodeon." }),
	    new WhiteCard({ desc : "Crippling debt." }),
	    new WhiteCard({ desc : "Kamikaze pilots." }),
	    new WhiteCard({ desc : "Teaching a robot to love." }),
	    new WhiteCard({ desc : "Police brutality." }),
	    new WhiteCard({ desc : "Horse meat." }),
	    new WhiteCard({ desc : "All you can eat shrimp for $4.99." }),
	    new WhiteCard({ desc : "Heteronormativity." }),
	    new WhiteCard({ desc : "Michael Jackson." }),
	    new WhiteCard({ desc : "A really cool hat." }),
	    new WhiteCard({ desc : "Copping a feel." }),
	    new WhiteCard({ desc : "Crystal meth." }),
	    new WhiteCard({ desc : "Shapeshifters." }),
	    new WhiteCard({ desc : "Fingering." }),
	    new WhiteCard({ desc : "A disappointing birthday party." }),
	    new WhiteCard({ desc : "Dental dams." }),
	    new WhiteCard({ desc : "My soul." }),
	    new WhiteCard({ desc : "A sausage festival." }),
	    new WhiteCard({ desc : "The chronic." }),
	    new WhiteCard({ desc : "Eugenics." }),
	    new WhiteCard({ desc : "Synergistic management solutions." }),
	    new WhiteCard({ desc : "RoboCop." }),
	    new WhiteCard({ desc : "Serfdom." }),
	    new WhiteCard({ desc : "Stephen Hawking talking dirty." }),
	    new WhiteCard({ desc : "Tangled Slinkys." }),
	    new WhiteCard({ desc : "Fiery poops." }),
	    new WhiteCard({ desc : "Public ridicule." }),
	    new WhiteCard({ desc : "That thing that electrocutes your abs." }),
	    new WhiteCard({ desc : "Picking up girls at the abortion clinic." }),
	    new WhiteCard({ desc : "Object permanence." }),
	    new WhiteCard({ desc : "GoGurt." }),
	    new WhiteCard({ desc : "Lockjaw." }),
	    new WhiteCard({ desc : "Attitude." }),
	    new WhiteCard({ desc : "Passable transvestites." }),
	    new WhiteCard({ desc : "Wet dreams." }),
	    new WhiteCard({ desc : "The Dance of the Sugar Plum Fairy." }),
	    new WhiteCard({ desc : "Firing a rifle into the air while balls deep in a squealing hog." }),
	    new WhiteCard({ desc : "Panda Sex." }),
	    new WhiteCard({ desc : "Necrophilia." }),
	    new WhiteCard({ desc : "Grave robbing." }),
	    new WhiteCard({ desc : "A bleached asshole." }),
	    new WhiteCard({ desc : "Muhammad (Praise Be Unto Him)." }),
	    new WhiteCard({ desc : "Multiple stab wounds." }),
	    new WhiteCard({ desc : "Stranger danger." }),
	    new WhiteCard({ desc : "A monkey smoking a cigar." }),
	    new WhiteCard({ desc : "Smegma." }),
	    new WhiteCard({ desc : "A live studio audience." }),
	    new WhiteCard({ desc : "Making a pouty face." }),
	    new WhiteCard({ desc : "The violation of our most basic human rights." }),
	    new WhiteCard({ desc : "Unfathomable stupidity." }),
	    new WhiteCard({ desc : "Sunshine and rainbows." }),
	    new WhiteCard({ desc : "Whipping it out." }),
	    new WhiteCard({ desc : "The token minority." }),
	    new WhiteCard({ desc : "The terrorists." }),
	    new WhiteCard({ desc : "The Three-Fifths compromise." }),
	    new WhiteCard({ desc : "A snapping turtle biting the tip of your penis." }),
	    new WhiteCard({ desc : "Vehicular manslaughter." }),
	    new WhiteCard({ desc : "Jibber-jabber." }),
	    new WhiteCard({ desc : "Emotions." }),
	    new WhiteCard({ desc : "Getting so angry that you pop a boner." }),
	    new WhiteCard({ desc : "Same-sex ice dancing." }),
	    new WhiteCard({ desc : "An M16 assault rifle." }),
	    new WhiteCard({ desc : "Man meat." }),
	    new WhiteCard({ desc : "Incest." }),
	    new WhiteCard({ desc : "A foul mouth." }),
	    new WhiteCard({ desc : "Flightless birds." }),
	    new WhiteCard({ desc : "Doing the right thing." }),
	    new WhiteCard({ desc : "When you fart and a little bit comes out." }),
	    new WhiteCard({ desc : "Frolicking." }),
	    new WhiteCard({ desc : "Being a dick to children." }),
	    new WhiteCard({ desc : "Poopy diapers." }),
	    new WhiteCard({ desc : "Filing Sean Hannity with helium and watching him float away." }),
	    new WhiteCard({ desc : "Raptor attacks." }),
	    new WhiteCard({ desc : "Swooping." }),
	    new WhiteCard({ desc : "Concealing a boner." }),
	    new WhiteCard({ desc : "Full frontal nudity." }),
	    new WhiteCard({ desc : "Vigorous jazz hands." }),
	    new WhiteCard({ desc : "Nipple blades." }),
	    new WhiteCard({ desc : "A bitch slap." }),
	    new WhiteCard({ desc : "Michelle Obama's arms." }),
	    new WhiteCard({ desc : "Mouth herpes." }),
	    new WhiteCard({ desc : "A robust mongoloid." }),
	    new WhiteCard({ desc : "Mutually-assured destruction." }),
	    new WhiteCard({ desc : "The rapture." }),
	    new WhiteCard({ desc : "Road head." }),
	    new WhiteCard({ desc : "Stalin." }),
	    new WhiteCard({ desc : "Lactation." }),
	    new WhiteCard({ desc : "Hurricane Katrina." }),
	    new WhiteCard({ desc : "The true meaning of Christmas." }),
	    new WhiteCard({ desc : "Self-loathing." }),
	    new WhiteCard({ desc : "A brain tumor." }),
	    new WhiteCard({ desc : "Dead babies." }),
	    new WhiteCard({ desc : "New Age music." }),
	    new WhiteCard({ desc : "A thermonuclear detonation." }),
	    new WhiteCard({ desc : "Geese." }),
	    new WhiteCard({ desc : "Kanye West." }),
	    new WhiteCard({ desc : "God." }),
	    new WhiteCard({ desc : "A spastic nerd." }),
	    new WhiteCard({ desc : "Harry Potter erotica." }),
	    new WhiteCard({ desc : "Kids with ass cancer." }),
	    new WhiteCard({ desc : "Lumberjack fantasies." }),
	    new WhiteCard({ desc : "The American Dream." }),
	    new WhiteCard({ desc : "Puberty." }),
	    new WhiteCard({ desc : "Sweet, sweet vengeance." }),
	    new WhiteCard({ desc : "Winking at old people." }),
	    new WhiteCard({ desc : "The taint; the grundle; the fleshy fun-bridge." }),
	    new WhiteCard({ desc : "Oompa - Loopmas." }),
	    new WhiteCard({ desc : "Authentic Mexican cusine." }),
	    new WhiteCard({ desc : "Preteens." }),
	    new WhiteCard({ desc : "The Little Engine That Could." }),
	    new WhiteCard({ desc : "Guys who don't call." }),
	    new WhiteCard({ desc : "Erectile dysfunction." }),
	    new WhiteCard({ desc : "Parting the Red Sea." }),
	    new WhiteCard({ desc : "Rush Limbaugh's soft, shitty body." }),
	    new WhiteCard({ desc : "Saxophone solos." }),
	    new WhiteCard({ desc : "Land mines." }),
	    new WhiteCard({ desc : "Capturing Newt Gingrich and forcing him to dance in a monkey suit." }),
	    new WhiteCard({ desc : "Me time." }),
	    new WhiteCard({ desc : "Nickelback." }),
	    new WhiteCard({ desc : "Vigilante justice." }),
	    new WhiteCard({ desc : "The South." }),
	    new WhiteCard({ desc : "Opposable thumbs." }),
	    new WhiteCard({ desc : "Ghosts." }),
	    new WhiteCard({ desc : "Alcoholism." }),
	    new WhiteCard({ desc : "Poorly-timed Holocaust jokes." }),
	    new WhiteCard({ desc : "Inappropriate yodeling." }),
	    new WhiteCard({ desc : "Battlefield amputations." }),
	    new WhiteCard({ desc : "Exactly what you'd expect." }),
	    new WhiteCard({ desc : "A time travel paradox." }),
	    new WhiteCard({ desc : "AXE Body Spray." }),
	    new WhiteCard({ desc : "Actually taking candy from a baby." }),
	    new WhiteCard({ desc : "Leaving an awkward voicemail." }),
	    new WhiteCard({ desc : "A sassy black woman." }),
	    new WhiteCard({ desc : "Being a motherfucking sorcerer." }),
	    new WhiteCard({ desc : "A mopey zoo lion." }),
	    new WhiteCard({ desc : "A murder most foul." }),
	    new WhiteCard({ desc : "A falcon with a cap on its head." }),
	    new WhiteCard({ desc : "Farting and walking away." }),
	    new WhiteCard({ desc : "A mating display." }),
	    new WhiteCard({ desc : "The Chinese gymnastics team." }),
	    new WhiteCard({ desc : "Friction." }),
	    new WhiteCard({ desc : "Asians who aren't good at math." }),
	    new WhiteCard({ desc : "Fear itself." }),
	    new WhiteCard({ desc : "A can of whoop-ass." }),
	    new WhiteCard({ desc : "Yeast." }),
	    new WhiteCard({ desc : "Lunchables." }),
	    new WhiteCard({ desc : "Licking things to claim them as your own." }),
	    new WhiteCard({ desc : "Vikings." }),
	    new WhiteCard({ desc : "The Kool-Aid Man." }),
	    new WhiteCard({ desc : "Hot cheese." }),
	    new WhiteCard({ desc : "Nicholas Cage." }),
	    new WhiteCard({ desc : "A defective condom." }),
	    new WhiteCard({ desc : "The inevitable heat death of the universe." }),
	    new WhiteCard({ desc : "Republicans." }),
	    new WhiteCard({ desc : "William Shatner." }),
	    new WhiteCard({ desc : "Tentacle porn." }),
	    new WhiteCard({ desc : "Sperm whales." }),
	    new WhiteCard({ desc : "Lady Gaga." }),
	    new WhiteCard({ desc : "Chunks of dead prostitutes." }),
	    new WhiteCard({ desc : "Gloryholes." }),
	    new WhiteCard({ desc : "Daddy issues." }),
	    new WhiteCard({ desc : "A mime having a stroke." }),
	    new WhiteCard({ desc : "White people." }),
	    new WhiteCard({ desc : "A lifetime of sadness." }),
	    new WhiteCard({ desc : "Tasteful sideboob." }),
	    new WhiteCard({ desc : "A sea of troubles." }),
	    new WhiteCard({ desc : "Nazis." }),
	    new WhiteCard({ desc : "A cooler full of organs." }),
	    new WhiteCard({ desc : "Giving 110%." }),
	    new WhiteCard({ desc : "Doin' it in the butt." }),
	    new WhiteCard({ desc : "John Wilkes Booth." }),
	    new WhiteCard({ desc : "Obesity." }),
	    new WhiteCard({ desc : "A homoerotic volleyball montage." }),
	    new WhiteCard({ desc : "Puppies." }),
	    new WhiteCard({ desc : "Natural male enhancement." }),
	    new WhiteCard({ desc : "Brown people." }),
	    new WhiteCard({ desc : "Dropping a chandelier on your enemies and riding the rope up." }),
	    new WhiteCard({ desc : "Soup that is too hot." }),
	    new WhiteCard({ desc : "Porn stars." }),
	    new WhiteCard({ desc : "Hormone injections." }),
	    new WhiteCard({ desc : "Pulling out." }),
	    new WhiteCard({ desc : "The Big Bang." }),
	    new WhiteCard({ desc : "Switching to Geico." }),
	    new WhiteCard({ desc : "Wearing underwear inside-out to avoid doing laundry." }),
	    new WhiteCard({ desc : "Rehab." }),
	    new WhiteCard({ desc : "Christopher Walken." }),
	    new WhiteCard({ desc : "Count Chocula." }),
	    new WhiteCard({ desc : "The Hamburglar." }),
	    new WhiteCard({ desc : "Not reciprocating oral sex." }),
	    new WhiteCard({ desc : "Aaron Burr." }),
	    new WhiteCard({ desc : "Hot people." }),
	    new WhiteCard({ desc : "Foreskin." }),
	    new WhiteCard({ desc : "Assless chaps." }),
	    new WhiteCard({ desc : "The miracle of childbirth." }),
	    new WhiteCard({ desc : "Waiting 'til marriage." }),
	    new WhiteCard({ desc : "Two midgets shitting in a bucket." }),
	    new WhiteCard({ desc : "Adderall." }),
	    new WhiteCard({ desc : "A sad handjob." }),
	    new WhiteCard({ desc : "Cheating in the Special Olympics." }),
	    new WhiteCard({ desc : "The glass ceiling." }),
	    new WhiteCard({ desc : "The hustle." }),
	    new WhiteCard({ desc : "Getting drunk on mouthwash." }),
	    new WhiteCard({ desc : "Bling." }),
	    new WhiteCard({ desc : "Breaking out into song and dance." }),
	    new WhiteCard({ desc : "A super Soaker full of cat pee." }),
	    new WhiteCard({ desc : "The underground Railroad." }),
	    new WhiteCard({ desc : "Home video of Oprah sobbing into a Lean Cuisine." }),
	    new WhiteCard({ desc : "The Rev. Dr. Martin Luther King Jr." }),
	    new WhiteCard({ desc : "Extremely tight pants." }),
	    new WhiteCard({ desc : "Third base." }),
	    new WhiteCard({ desc : "Waking up half-naked in a Denny's parking lot." }),
	    new WhiteCard({ desc : "Golden showers." }),
	    new WhiteCard({ desc : "White privilege." }),
	    new WhiteCard({ desc : "Hope." }),
	    new WhiteCard({ desc : "Taking off your shirt." }),
	    new WhiteCard({ desc : "Smallpox blankets." }),
	    new WhiteCard({ desc : "Ethnic cleansing." }),
	    new WhiteCard({ desc : "Queefing." }),
	    new WhiteCard({ desc : "Helplessly giggling at the mention of Hutus and Tutsis." }),
	    new WhiteCard({ desc : "Getting really high." }),
	    new WhiteCard({ desc : "Natural selection." }),
	    new WhiteCard({ desc : "A gassy antelope." }),
	    new WhiteCard({ desc : "My sex life." }),
	    new WhiteCard({ desc : "Arnold Schwarzenegger." }),
	    new WhiteCard({ desc : "Pretending to care." }),
	    new WhiteCard({ desc : "Ronald Reagan." }),
	    new WhiteCard({ desc : "Toni Morrison's vagina." }),
	    new WhiteCard({ desc : "Pterodactyl eggs." }),
	    new WhiteCard({ desc : "A death ray." }),
	    new WhiteCard({ desc : "BATMAN!!!" }),
	    new WhiteCard({ desc : "Homeless people." }),
	    new WhiteCard({ desc : "Racially-biased SAT questions." }),
	    new WhiteCard({ desc : "Centaurs." }),
	    new WhiteCard({ desc : "A salty surprise." }),
	    new WhiteCard({ desc : "72 virgins." }),
	    new WhiteCard({ desc : "Embryonic stem cells." }),
	    new WhiteCard({ desc : "Pixelated bukkake." }),
	    new WhiteCard({ desc : "Seppuku." }),
	    new WhiteCard({ desc : "An icepick lobotomy." }),
	    new WhiteCard({ desc : "Stormtroopers." }),
	    new WhiteCard({ desc : "Menstural rage." }),
	    new WhiteCard({ desc : "Passing a kidney stone." }),
	    new WhiteCard({ desc : "An uppercut." }),
	    new WhiteCard({ desc : "Shaquille O'Neal's acting career." }),
	    new WhiteCard({ desc : "Horrifying laser hair removal accidents." }),
	    new WhiteCard({ desc : "Autocannibalism." }),
	    new WhiteCard({ desc : "A fetus." }),
	    new WhiteCard({ desc : "Riding off into the sunset." }),
	    new WhiteCard({ desc : "Goblins." }),
	    new WhiteCard({ desc : "Eating the last known bison." }),
	    new WhiteCard({ desc : "Shiny objects." }),
	    new WhiteCard({ desc : "Being rich." }),
	    new WhiteCard({ desc : "A Bop It." }),
	    new WhiteCard({ desc : "Leprosy." }),
	    new WhiteCard({ desc : "World peace." }),
	    new WhiteCard({ desc : "Dick fingers." }),
	    new WhiteCard({ desc : "Chainsaw for hands." }),
	    new WhiteCard({ desc : "The Make-A-Wish Foundation." }),
	    new WhiteCard({ desc : "Britney Spears at 55." }),
	    new WhiteCard({ desc : "Laying an egg." }),
	    new WhiteCard({ desc : "The folly of man." }),
	    new WhiteCard({ desc : "My genitals." }),
	    new WhiteCard({ desc : "Grandma." }),
	    new WhiteCard({ desc : "Flesh-eating bacteria." }),
	    new WhiteCard({ desc : "Poor people." }),
	    new WhiteCard({ desc : "50,000 volts straight to the nipples." }),
	    new WhiteCard({ desc : "Active listening." }),
	    new WhiteCard({ desc : "The Ubermensch." }),
	    new WhiteCard({ desc : "Poor life choices." }),
	    new WhiteCard({ desc : "Alter boys." }),
	    new WhiteCard({ desc : "My vagina." }),
	    new WhiteCard({ desc : "Pac-Man uncontrollably guzzling cum." }),
	    new WhiteCard({ desc : "Sniffing glue." }),
	    new WhiteCard({ desc : "The placenta." }),
	    new WhiteCard({ desc : "The profoundly handicapped." }),
	    new WhiteCard({ desc : "Spontaneous human combustion." }),
	    new WhiteCard({ desc : "The KKK." }),
	    new WhiteCard({ desc : "The clitoris." }),
	    new WhiteCard({ desc : "Not wearing pants." }),
	    new WhiteCard({ desc : "Date rape." }),
	    new WhiteCard({ desc : "Black people." }),
	    new WhiteCard({ desc : "A bucket of fish heads." }),
	    new WhiteCard({ desc : "Hospice care." }),
	    new WhiteCard({ desc : "Passive-aggressive Post-it notes." }),
	    new WhiteCard({ desc : "Fancy Feast." }),
	    new WhiteCard({ desc : "The heart of a child." }),
	    new WhiteCard({ desc : "Sharing needles." }),
	    new WhiteCard({ desc : "Scalping." }),
	    new WhiteCard({ desc : "A look-see." }),
	    new WhiteCard({ desc : "Getting married, having a few kids, buying some stuff, retiring, and dying." }),
	    new WhiteCard({ desc : "Sean Penn." }),
	    new WhiteCard({ desc : "Sean Connery." }),
	    new WhiteCard({ desc : "Expecting a burp and vomiting on the floor." }),
	    new WhiteCard({ desc : "Wifely duties." }),
	    new WhiteCard({ desc : "A pyramid of severed heads." }),
	    new WhiteCard({ desc : "Genghis Khan." }),
	    new WhiteCard({ desc : "Historically black colleges." }),
	    new WhiteCard({ desc : "Raping and pillaging." }),
	    new WhiteCard({ desc : "A subscription to Men's Fitness." }),
	    new WhiteCard({ desc : "The milk man." }),
	    new WhiteCard({ desc : "Friendly fire." }),
	    new WhiteCard({ desc : "Women's suffrage." }),
	    new WhiteCard({ desc : "AIDS." }),
	    new WhiteCard({ desc : "Former President George W. Bush." }),
	    new WhiteCard({ desc : "8 oz. of sweet Mexican black-tar heroin." }),
	    new WhiteCard({ desc : "Half-assed foreplay." }),
	    new WhiteCard({ desc : "Edible underpants." }),
	    new WhiteCard({ desc : "My collection of high-tech sex toys." }),
	    new WhiteCard({ desc : "The Forced." }),
	    new WhiteCard({ desc : "Bees?" }),
	    new WhiteCard({ desc : "Loose lips." }),
	    new WhiteCard({ desc : "Jerking off into a pool of children's tears." }),
	    new WhiteCard({ desc : "A micropig wearing a tiny raincoat and booties." }),
	    new WhiteCard({ desc : "A hot mess." }),
	    new WhiteCard({ desc : "Masturbation." }),
	    new WhiteCard({ desc : "Tom Cruise." }),
	    new WhiteCard({ desc : "A balanced breakfast." }),
	    new WhiteCard({ desc : "Anal beads." }),
	    new WhiteCard({ desc : "Drinking alone." }),
	    new WhiteCard({ desc : "Cards Against Humanity." }),
	    new WhiteCard({ desc : "Coat hanger abortions." }),
	    new WhiteCard({ desc : "Used panties." }),
	    new WhiteCard({ desc : "Cuddling." }),
	    new WhiteCard({ desc : "Wiping her butt." }),
	    new WhiteCard({ desc : "Domino's Oreo Dessert Pizza." }),
	    new WhiteCard({ desc : "A zesty breakfast burrito." }),
	    new WhiteCard({ desc : "Morgan Freeman's voice." }),
	    new WhiteCard({ desc : "A middle-aged man on roller skates." }),
	    new WhiteCard({ desc : "Gandhi." }),
	    new WhiteCard({ desc : "The penny whistle solo from \"My Heart Will Go On\"." }),
	    new WhiteCard({ desc : "Spectacular abs." }),
	    new WhiteCard({ desc : "Keanu Reeves." }),
	    new WhiteCard({ desc : "Child beauty pageants." }),
	    new WhiteCard({ desc : "Child abuse." }),
	    new WhiteCard({ desc : "Bill Nye the Science Guy." }),
	    new WhiteCard({ desc : "Science." }),
	    new WhiteCard({ desc : "A tribe of warrior women." }),
	    new WhiteCard({ desc : "Viagra." }),
	    new WhiteCard({ desc : "Her Majesty, Queen Elizabeth II." }),
	    new WhiteCard({ desc : "The entire Mormon Tabernacle Choir." }),
	    new WhiteCard({ desc : "Hulk Hogan." }),
	    new WhiteCard({ desc : "Take-backsies." }),
	    new WhiteCard({ desc : "An erection that lasts longer than four hours." })];
}